version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - TZ=UTC
      - POSTGRES_DB=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    command: postgres -c 'max_connections=10000'

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: --requirepass redis

